package org.mraz.moose.dao.enums.subtype.moose;
/**
 * Defines the GroupSubclassType enumeration.
 * 
 * @author autogenerated
 *
 */
public enum GroupSubclassType {

	/** Enum Constant. */
	NOT_A_CHILD,
	/** Enum Constant. */
	GROUP_SKILLS;

}
