package org.mraz.moose.dao.enums.subtype.moose;
/**
 * Defines the PlayerSubclassType enumeration.
 * 
 * @author autogenerated
 *
 */
public enum PlayerSubclassType {

	/** Enum Constant. */
	ALIASES,
	/** Enum Constant. */
	NOT_A_CHILD,
	/** Enum Constant. */
	PLAYER_DEITY,
	/** Enum Constant. */
	PLAYER_GLADIATOR,
	/** Enum Constant. */
	PLAYER_GROUP,
	/** Enum Constant. */
	PLAYER_LASTS,
	/** Enum Constant. */
	PLAYER_NOTES,
	/** Enum Constant. */
	PLAYER_SKILLS,
	/** Enum Constant. */
	PLAYER_STATS;

}
