package org.mraz.moose.dao.services.data;

import java.io.Serializable;
import org.mraz.moose.dao.factories.moose.*;
import org.mraz.moose.dao.model.obj.moose.Aliases;
import org.mraz.moose.dao.model.obj.moose.Attributes;
import org.mraz.moose.dao.model.obj.moose.Clans;
import org.mraz.moose.dao.model.obj.moose.Deity;
import org.mraz.moose.dao.model.obj.moose.Group;
import org.mraz.moose.dao.model.obj.moose.GroupSkills;
import org.mraz.moose.dao.model.obj.moose.Player;
import org.mraz.moose.dao.model.obj.moose.PlayerDeity;
import org.mraz.moose.dao.model.obj.moose.PlayerGladiator;
import org.mraz.moose.dao.model.obj.moose.PlayerGroup;
import org.mraz.moose.dao.model.obj.moose.PlayerLasts;
import org.mraz.moose.dao.model.obj.moose.PlayerNotes;
import org.mraz.moose.dao.model.obj.moose.PlayerSkills;
import org.mraz.moose.dao.model.obj.moose.PlayerStats;
import org.mraz.moose.dao.model.obj.moose.Races;
import org.mraz.moose.dao.model.obj.moose.SkillSpell;
import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.SQLQuery;
import org.hibernate.ReplicationMode;
import org.hibernate.Session;
import java.util.Collection;
import com.felees.hbnpojogen.persistence.IPojoGenEntity;
import java.util.concurrent.ConcurrentHashMap;
import java.util.Map;
import com.felees.hbnpojogen.persistence.GenericDAO;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.hibernate.LockMode;
import org.hibernate.SessionFactory;
import org.hibernate.proxy.HibernateProxy;
/** 
 * Data layer.
 * @author autogenerated
 */
@org.springframework.stereotype.Component
public class DataLayerMooseImpl implements DataLayerMoose {
	/** Singleton reference to this class. */
	private static DataLayerMoose instance;
	/** map lock. */
	private static Object daoMapLock = new Object();

	/** Internal handle. */
	private static Map<Class<?>, GenericDAO<?, ?>> daoMap = null; 
	
		/** Inner handle. */
	private static ApplicationContext context;
 /** Sessionfactory in use. Filled in by Spring. */ 
    private SessionFactory sessionFactory = null;
	
	/** Handle to get back ourselves and perform correct injection. 
	 * @param ctxt filled by spring
	 */
	@Autowired
	public void setApplicationContext(ApplicationContext ctxt) {
		DataLayerMooseImpl.context = ctxt;
	}
	
	
		
 	/**
     * Set session factory.
     * @param sessionFactory sessionfactory to use. 
     */
    @Autowired
    public void setSessionFactory(SessionFactory sessionFactory) {
        this.sessionFactory = sessionFactory;
    }
    
    /** 
	* Returns a DAO instance of the given type.
	* @param <T> Type
	* @param persistentObject to get
	* @return GenericDAO<T, ?> object
     */
    @SuppressWarnings("unchecked")
    private <T> GenericDAO<T, ?> getDAO(final T persistentObject) {
		T persistent = persistentObject;

		synchronized (daoMapLock) {
    		if (daoMap == null) {
    			daoMap = new ConcurrentHashMap<Class<?>, GenericDAO<?, ?>>(); 
	 	   		daoMap.put(Aliases.class, HibernateMooseDaoFactory.getAliasesDao());
	 	   		daoMap.put(Attributes.class, HibernateMooseDaoFactory.getAttributesDao());
	 	   		daoMap.put(Clans.class, HibernateMooseDaoFactory.getClansDao());
	 	   		daoMap.put(Deity.class, HibernateMooseDaoFactory.getDeityDao());
	 	   		daoMap.put(Group.class, HibernateMooseDaoFactory.getGroupDao());
	 	   		daoMap.put(GroupSkills.class, HibernateMooseDaoFactory.getGroupSkillsDao());
	 	   		daoMap.put(Player.class, HibernateMooseDaoFactory.getPlayerDao());
	 	   		daoMap.put(PlayerDeity.class, HibernateMooseDaoFactory.getPlayerDeityDao());
	 	   		daoMap.put(PlayerGladiator.class, HibernateMooseDaoFactory.getPlayerGladiatorDao());
	 	   		daoMap.put(PlayerGroup.class, HibernateMooseDaoFactory.getPlayerGroupDao());
	 	   		daoMap.put(PlayerLasts.class, HibernateMooseDaoFactory.getPlayerLastsDao());
	 	   		daoMap.put(PlayerNotes.class, HibernateMooseDaoFactory.getPlayerNotesDao());
	 	   		daoMap.put(PlayerSkills.class, HibernateMooseDaoFactory.getPlayerSkillsDao());
	 	   		daoMap.put(PlayerStats.class, HibernateMooseDaoFactory.getPlayerStatsDao());
	 	   		daoMap.put(Races.class, HibernateMooseDaoFactory.getRacesDao());
	 	   		daoMap.put(SkillSpell.class, HibernateMooseDaoFactory.getSkillSpellDao());
    		}
		 }
		if (persistentObject instanceof HibernateProxy) {
			persistent = (T) ((HibernateProxy) persistentObject).getHibernateLazyInitializer().getImplementation();
		} 
		
		GenericDAO<T, ?> result = (GenericDAO<T, ?>) daoMap.get(persistent.getClass());
		if (result == null) {
			throw new IllegalAccessError("The given object is of an incorrect type. ");
		}
		return result;
    }

    /**
     * Deletes the given object from disk.
     * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to delete
     */
    public <T> void delete(T persistentObject) {
    	    	getDAO(persistentObject).delete(persistentObject);
    }
    /**
     * Refresh the object $class.className from disk.
     * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to reload
     */
    public <T> void refresh(T persistentObject) {
	    	getDAO(persistentObject).refresh(persistentObject);
    }

    /**
     * Saves the given object to disk.
     * @param persistentObject Object to save
	 * @param <T> A DataLayerObject-derived type
     * @return Identifier of saved object 
     */
    public <T> Serializable save(T persistentObject) {
        return getDAO(persistentObject).save(persistentObject);
    }
    /**
     * Saves or updates the given $class.className object to disk.
	 * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to save 
     */
    public <T> void saveOrUpdate(T persistentObject) {
        getDAO(persistentObject).saveOrUpdate(persistentObject);
    }
    /**
     * Updates the given object to disk.
	 * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to update 
     */
    public <T> void update(T persistentObject) {
        getDAO(persistentObject).update(persistentObject);
    }


    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Aliases obj) directly
     * @param id Identifier to delete
     */
    public void deleteAliases(final Date id)  {
        HibernateMooseDaoFactory.getAliasesDao().delete(loadAliases(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Aliases object
     */
    public Aliases loadAliases(final Date id) {
        return HibernateMooseDaoFactory.getAliasesDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public Aliases getAliases(final Date id) {
        return HibernateMooseDaoFactory.getAliasesDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Attributes obj) directly
     * @param id Identifier to delete
     */
    public void deleteAttributes(final Long id)  {
        HibernateMooseDaoFactory.getAttributesDao().delete(loadAttributes(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Attributes object
     */
    public Attributes loadAttributes(final Long id) {
        return HibernateMooseDaoFactory.getAttributesDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public Attributes getAttributes(final Long id) {
        return HibernateMooseDaoFactory.getAttributesDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Clans obj) directly
     * @param id Identifier to delete
     */
    public void deleteClans(final Long id)  {
        HibernateMooseDaoFactory.getClansDao().delete(loadClans(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Clans object
     */
    public Clans loadClans(final Long id) {
        return HibernateMooseDaoFactory.getClansDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public Clans getClans(final Long id) {
        return HibernateMooseDaoFactory.getClansDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Deity obj) directly
     * @param id Identifier to delete
     */
    public void deleteDeity(final Long id)  {
        HibernateMooseDaoFactory.getDeityDao().delete(loadDeity(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Deity object
     */
    public Deity loadDeity(final Long id) {
        return HibernateMooseDaoFactory.getDeityDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public Deity getDeity(final Long id) {
        return HibernateMooseDaoFactory.getDeityDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Group obj) directly
     * @param id Identifier to delete
     */
    public void deleteGroup(final Long id)  {
        HibernateMooseDaoFactory.getGroupDao().delete(loadGroup(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Group object
     */
    public Group loadGroup(final Long id) {
        return HibernateMooseDaoFactory.getGroupDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public Group getGroup(final Long id) {
        return HibernateMooseDaoFactory.getGroupDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (GroupSkills obj) directly
     * @param id Identifier to delete
     */
    public void deleteGroupSkills(final Long id)  {
        HibernateMooseDaoFactory.getGroupSkillsDao().delete(loadGroupSkills(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a GroupSkills object
     */
    public GroupSkills loadGroupSkills(final Long id) {
        return HibernateMooseDaoFactory.getGroupSkillsDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public GroupSkills getGroupSkills(final Long id) {
        return HibernateMooseDaoFactory.getGroupSkillsDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Player obj) directly
     * @param id Identifier to delete
     */
    public void deletePlayer(final Date id)  {
        HibernateMooseDaoFactory.getPlayerDao().delete(loadPlayer(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Player object
     */
    public Player loadPlayer(final Date id) {
        return HibernateMooseDaoFactory.getPlayerDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public Player getPlayer(final Date id) {
        return HibernateMooseDaoFactory.getPlayerDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (PlayerDeity obj) directly
     * @param id Identifier to delete
     */
    public void deletePlayerDeity(final Date id)  {
        HibernateMooseDaoFactory.getPlayerDeityDao().delete(loadPlayerDeity(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a PlayerDeity object
     */
    public PlayerDeity loadPlayerDeity(final Date id) {
        return HibernateMooseDaoFactory.getPlayerDeityDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public PlayerDeity getPlayerDeity(final Date id) {
        return HibernateMooseDaoFactory.getPlayerDeityDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (PlayerGladiator obj) directly
     * @param id Identifier to delete
     */
    public void deletePlayerGladiator(final Date id)  {
        HibernateMooseDaoFactory.getPlayerGladiatorDao().delete(loadPlayerGladiator(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a PlayerGladiator object
     */
    public PlayerGladiator loadPlayerGladiator(final Date id) {
        return HibernateMooseDaoFactory.getPlayerGladiatorDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public PlayerGladiator getPlayerGladiator(final Date id) {
        return HibernateMooseDaoFactory.getPlayerGladiatorDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (PlayerGroup obj) directly
     * @param id Identifier to delete
     */
    public void deletePlayerGroup(final Date id)  {
        HibernateMooseDaoFactory.getPlayerGroupDao().delete(loadPlayerGroup(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a PlayerGroup object
     */
    public PlayerGroup loadPlayerGroup(final Date id) {
        return HibernateMooseDaoFactory.getPlayerGroupDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public PlayerGroup getPlayerGroup(final Date id) {
        return HibernateMooseDaoFactory.getPlayerGroupDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (PlayerLasts obj) directly
     * @param id Identifier to delete
     */
    public void deletePlayerLasts(final Date id)  {
        HibernateMooseDaoFactory.getPlayerLastsDao().delete(loadPlayerLasts(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a PlayerLasts object
     */
    public PlayerLasts loadPlayerLasts(final Date id) {
        return HibernateMooseDaoFactory.getPlayerLastsDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public PlayerLasts getPlayerLasts(final Date id) {
        return HibernateMooseDaoFactory.getPlayerLastsDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (PlayerNotes obj) directly
     * @param id Identifier to delete
     */
    public void deletePlayerNotes(final Date id)  {
        HibernateMooseDaoFactory.getPlayerNotesDao().delete(loadPlayerNotes(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a PlayerNotes object
     */
    public PlayerNotes loadPlayerNotes(final Date id) {
        return HibernateMooseDaoFactory.getPlayerNotesDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public PlayerNotes getPlayerNotes(final Date id) {
        return HibernateMooseDaoFactory.getPlayerNotesDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (PlayerSkills obj) directly
     * @param id Identifier to delete
     */
    public void deletePlayerSkills(final Date id)  {
        HibernateMooseDaoFactory.getPlayerSkillsDao().delete(loadPlayerSkills(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a PlayerSkills object
     */
    public PlayerSkills loadPlayerSkills(final Date id) {
        return HibernateMooseDaoFactory.getPlayerSkillsDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public PlayerSkills getPlayerSkills(final Date id) {
        return HibernateMooseDaoFactory.getPlayerSkillsDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (PlayerStats obj) directly
     * @param id Identifier to delete
     */
    public void deletePlayerStats(final Date id)  {
        HibernateMooseDaoFactory.getPlayerStatsDao().delete(loadPlayerStats(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a PlayerStats object
     */
    public PlayerStats loadPlayerStats(final Date id) {
        return HibernateMooseDaoFactory.getPlayerStatsDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public PlayerStats getPlayerStats(final Date id) {
        return HibernateMooseDaoFactory.getPlayerStatsDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Races obj) directly
     * @param id Identifier to delete
     */
    public void deleteRaces(final Long id)  {
        HibernateMooseDaoFactory.getRacesDao().delete(loadRaces(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Races object
     */
    public Races loadRaces(final Long id) {
        return HibernateMooseDaoFactory.getRacesDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public Races getRaces(final Long id) {
        return HibernateMooseDaoFactory.getRacesDao().get(id);
    }  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (SkillSpell obj) directly
     * @param id Identifier to delete
     */
    public void deleteSkillSpell(final Long id)  {
        HibernateMooseDaoFactory.getSkillSpellDao().delete(loadSkillSpell(id));
    }
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a SkillSpell object
     */
    public SkillSpell loadSkillSpell(final Long id) {
        return HibernateMooseDaoFactory.getSkillSpellDao().load(id);
    }
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     public SkillSpell getSkillSpell(final Long id) {
        return HibernateMooseDaoFactory.getSkillSpellDao().get(id);
    }  
    /** Returns a singleton instance of this class.
     * @return an singleton instance
     */
    public static synchronized DataLayerMoose getInstance() {
        
        if (instance == null) {
        	if (context == null) {
        		throw new IllegalStateException("Context is null. Make sure Spring is initialized.");
        	}
     		instance = (DataLayerMoose) context.getBean("dataLayerMooseImpl");
        }
        
        return instance; 
    }
    /** Returns a query handle.
     * @param query Query to use
     * @return A query instance
     */
     public Query createQuery(final String query) {
        return this.sessionFactory.getCurrentSession().createQuery(query);
    }
    /** Returns a criteria handle.
     * @param criteria Criteria to use
     * @return A criteria instance
     */
     public Criteria createCriteria(final String criteria) {
        return this.sessionFactory.getCurrentSession().createCriteria(criteria);
    }
    /** Returns a Query handle based on your package-level named query.
     * @param query Query to use
     * @return A query instance
     */
     public Query getNamedQuery(final String query) {
        return this.sessionFactory.getCurrentSession().getNamedQuery(query);
    }
    /** Create a new Criteria instance, for the given entity class, or a superclass of an entity class.
	* @param persistentObject a class, which is persistent, or has persistent subclasses 
	* @return Criteria instance
	*/
	@SuppressWarnings("unchecked")
	public Criteria createCriteria(Class persistentObject) {
        return this.sessionFactory.getCurrentSession().createCriteria(persistentObject);
    }
    /** Flushes the currently open session.
	*/
	public void flushSession() {
        this.sessionFactory.getCurrentSession().flush();
    }
    /** Clears the currently open session.
	*/
	public void clearSession() {
        this.sessionFactory.getCurrentSession().clear();
    }
    /** Flushes and clears the currently open session.
	*/
	public void flushAndClearSession() {
		flushSession();
		clearSession();
    }
	/** Call currentSession.replicate.
	 * @param obj to replicate
	 * @param replicationMode mode
	 */ 
	public void replicate(Object obj, ReplicationMode replicationMode) {
		this.sessionFactory.getCurrentSession().replicate(obj, replicationMode);
	}
	/** Hibernate Merge. 
	 * @param obj to merge
	 * @return obj merged.
	 */
	public Object merge(Object obj) {
		return this.sessionFactory.getCurrentSession().merge(obj);
	}
	/** Returns the current session.
	 * @return the currently active session
	 */
	public Session getCurrentSession() {
		return this.sessionFactory.getCurrentSession();
	}
	/** Returns a query handle.
     * @param query Query to use
     * @return A query instance
     */
     public SQLQuery createSQLQuery(final String query) {
        return this.sessionFactory.getCurrentSession().createSQLQuery(query);
    }
    /** Remove this instance from the session cache. 
	 * Changes to the instance will not be synchronized with the database
	 * @param obj object to evict
	 */
	public void evict(Object obj) {
        this.sessionFactory.getCurrentSession().evict(obj);
    }
    /**
     * Return the persistent instance of the given entity class with the given 
     * identifier, or null if there is no such persistent instance. 
     * (If the instance, or a proxy for the instance, is already 
     * associated with the session, return that instance or proxy)
     *
     * @param clazz a persistent class
     * @param id a valid identifier of an existing persistent instance of the class
     * @return a persistent instance or null
     * @throws HibernateException
     */
	public Object get(Class<?> clazz, Serializable id) throws HibernateException {
        return this.sessionFactory.getCurrentSession().get(clazz, id);
    }	


    /**
     * Return the persistent instance of the given entity class with the given identifier, assuming that the instance exists.
     *You should not use this method to determine if an instance exists (use get() instead). Use this only to retrieve an instance that you assume exists, where non-existence would be an actual error.
     *
     * @param clazz a persistent class
     * @param id a valid identifier of an existing persistent instance of the class
     * @return the persistent instance or proxy
     * @throws HibernateException
     */
	public Object load(Class<?> clazz, Serializable id) throws HibernateException {
        return this.sessionFactory.getCurrentSession().load(clazz, id);  
    }
	/**
	 * Reattaches the given entity to the current session using LockMode.NONE
	 *
	 * @param entity to reattach
	 */
	public void reattachEntityWithNoLock(IPojoGenEntity entity) {
		if (entity != null) {
        		this.sessionFactory.getCurrentSession().lock(entity, LockMode.NONE);
    		}
	}
	/**
	 * Reattaches the given entities to the current session.
	 *
	 * @param entities to attach
	 */
	public void reattachEntitiesWithNoLock(Collection<? extends IPojoGenEntity> entities) {
   		if (entities != null) {
		       for (IPojoGenEntity entity : entities) {
            		this.sessionFactory.getCurrentSession().lock(entity, LockMode.NONE);
        		 }
    		}
	}}

