package org.mraz.moose.dao.services.data;

import java.io.Serializable;
import org.mraz.moose.dao.model.obj.moose.Aliases;
import org.mraz.moose.dao.model.obj.moose.Attributes;
import org.mraz.moose.dao.model.obj.moose.Clans;
import org.mraz.moose.dao.model.obj.moose.Deity;
import org.mraz.moose.dao.model.obj.moose.Group;
import org.mraz.moose.dao.model.obj.moose.GroupSkills;
import org.mraz.moose.dao.model.obj.moose.Player;
import org.mraz.moose.dao.model.obj.moose.PlayerDeity;
import org.mraz.moose.dao.model.obj.moose.PlayerGladiator;
import org.mraz.moose.dao.model.obj.moose.PlayerGroup;
import org.mraz.moose.dao.model.obj.moose.PlayerLasts;
import org.mraz.moose.dao.model.obj.moose.PlayerNotes;
import org.mraz.moose.dao.model.obj.moose.PlayerSkills;
import org.mraz.moose.dao.model.obj.moose.PlayerStats;
import org.mraz.moose.dao.model.obj.moose.Races;
import org.mraz.moose.dao.model.obj.moose.SkillSpell;
import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.SQLQuery;
import org.hibernate.ReplicationMode;
import org.hibernate.Session;
import java.util.Collection;
import com.felees.hbnpojogen.persistence.IPojoGenEntity;
/** 
 * Data layer.
 * @author autogenerated
 */
public interface DataLayerMoose {

    /**
     * Deletes the given object from disk.
     * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to delete
     */
    <T> void delete(T persistentObject);
    /**
     * Refresh the object $class.className from disk.
     * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to reload
     */
    <T> void refresh(T persistentObject);

    /**
     * Saves the given object to disk.
     * @param persistentObject Object to save
	 * @param <T> A DataLayerObject-derived type
     * @return Identifier of saved object 
     */
    <T> Serializable save(T persistentObject);
    /**
     * Saves or updates the given $class.className object to disk.
	 * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to save 
     */
    <T> void saveOrUpdate(T persistentObject);
    /**
     * Updates the given object to disk.
	 * @param <T> A DataLayerObject-derived type
     * @param persistentObject Object to update 
     */
    <T> void update(T persistentObject);


    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Aliases obj) directly
     * @param id Identifier to delete
     */
    void deleteAliases(final Date id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Aliases object
     */
    Aliases loadAliases(final Date id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Aliases getAliases(final Date id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Attributes obj) directly
     * @param id Identifier to delete
     */
    void deleteAttributes(final Long id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Attributes object
     */
    Attributes loadAttributes(final Long id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Attributes getAttributes(final Long id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Clans obj) directly
     * @param id Identifier to delete
     */
    void deleteClans(final Long id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Clans object
     */
    Clans loadClans(final Long id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Clans getClans(final Long id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Deity obj) directly
     * @param id Identifier to delete
     */
    void deleteDeity(final Long id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Deity object
     */
    Deity loadDeity(final Long id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Deity getDeity(final Long id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Group obj) directly
     * @param id Identifier to delete
     */
    void deleteGroup(final Long id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Group object
     */
    Group loadGroup(final Long id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Group getGroup(final Long id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (GroupSkills obj) directly
     * @param id Identifier to delete
     */
    void deleteGroupSkills(final Long id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a GroupSkills object
     */
    GroupSkills loadGroupSkills(final Long id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     GroupSkills getGroupSkills(final Long id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Player obj) directly
     * @param id Identifier to delete
     */
    void deletePlayer(final Date id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Player object
     */
    Player loadPlayer(final Date id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Player getPlayer(final Date id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (PlayerDeity obj) directly
     * @param id Identifier to delete
     */
    void deletePlayerDeity(final Date id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a PlayerDeity object
     */
    PlayerDeity loadPlayerDeity(final Date id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     PlayerDeity getPlayerDeity(final Date id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (PlayerGladiator obj) directly
     * @param id Identifier to delete
     */
    void deletePlayerGladiator(final Date id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a PlayerGladiator object
     */
    PlayerGladiator loadPlayerGladiator(final Date id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     PlayerGladiator getPlayerGladiator(final Date id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (PlayerGroup obj) directly
     * @param id Identifier to delete
     */
    void deletePlayerGroup(final Date id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a PlayerGroup object
     */
    PlayerGroup loadPlayerGroup(final Date id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     PlayerGroup getPlayerGroup(final Date id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (PlayerLasts obj) directly
     * @param id Identifier to delete
     */
    void deletePlayerLasts(final Date id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a PlayerLasts object
     */
    PlayerLasts loadPlayerLasts(final Date id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     PlayerLasts getPlayerLasts(final Date id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (PlayerNotes obj) directly
     * @param id Identifier to delete
     */
    void deletePlayerNotes(final Date id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a PlayerNotes object
     */
    PlayerNotes loadPlayerNotes(final Date id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     PlayerNotes getPlayerNotes(final Date id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (PlayerSkills obj) directly
     * @param id Identifier to delete
     */
    void deletePlayerSkills(final Date id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a PlayerSkills object
     */
    PlayerSkills loadPlayerSkills(final Date id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     PlayerSkills getPlayerSkills(final Date id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (PlayerStats obj) directly
     * @param id Identifier to delete
     */
    void deletePlayerStats(final Date id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a PlayerStats object
     */
    PlayerStats loadPlayerStats(final Date id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     PlayerStats getPlayerStats(final Date id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (Races obj) directly
     * @param id Identifier to delete
     */
    void deleteRaces(final Long id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a Races object
     */
    Races loadRaces(final Long id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     Races getRaces(final Long id);  

    /** Deletes an object of a given Id. 
     * Will load the object internally so consider using delete (SkillSpell obj) directly
     * @param id Identifier to delete
     */
    void deleteSkillSpell(final Long id);
	
    /**
     * Loads the given Object.
     * @param id Identifier to load
     * @return a SkillSpell object
     */
    SkillSpell loadSkillSpell(final Long id);
    /**
     * Loads the given Object.
     * @param id Id to load
     * @return An object of type T
     */
     SkillSpell getSkillSpell(final Long id);  
    /** Returns a query handle.
     * @param query Query to use
     * @return A query instance
     */
     Query createQuery(final String query);
    /** Returns a criteria handle.
     * @param criteria Criteria to use
     * @return A criteria instance
     */
     Criteria createCriteria(final String criteria);
    /** Returns a Query handle based on your package-level named query.
     * @param query Query to use
     * @return A query instance
     */
     Query getNamedQuery(final String query);
    /** Create a new Criteria instance, for the given entity class, or a superclass of an entity class.
	* @param persistentObject a class, which is persistent, or has persistent subclasses 
	* @return Criteria instance
	*/
	@SuppressWarnings("unchecked")
	Criteria createCriteria(Class persistentObject);
    /** Flushes the currently open session.
	*/
	void flushSession();
    /** Clears the currently open session.
	*/
	void clearSession();
    /** Flushes and clears the currently open session.
	*/
	void flushAndClearSession();
	/** Call currentSession.replicate.
	 * @param obj to replicate
	 * @param replicationMode mode
	 */ 
	void replicate(Object obj, ReplicationMode replicationMode);
	/** Hibernate Merge. 
	 * @param obj to merge
	 * @return obj merged.
	 */
	Object merge(Object obj);
	/** Returns the current session.
	 * @return the currently active session
	 */
	Session getCurrentSession();
	/** Returns a query handle.
     * @param query Query to use
     * @return A query instance
     */
     SQLQuery createSQLQuery(final String query);
    /** Remove this instance from the session cache. 
	 * Changes to the instance will not be synchronized with the database
	 * @param obj object to evict
	 */
	void evict(Object obj);
    /**
     * Return the persistent instance of the given entity class with the given 
     * identifier, or null if there is no such persistent instance. 
     * (If the instance, or a proxy for the instance, is already 
     * associated with the session, return that instance or proxy)
     *
     * @param clazz a persistent class
     * @param id a valid identifier of an existing persistent instance of the class
     * @return a persistent instance or null
     * @throws HibernateException
     */
	Object get(Class<?> clazz, Serializable id) throws HibernateException;	


    /**
     * Return the persistent instance of the given entity class with the given identifier, assuming that the instance exists.
     *You should not use this method to determine if an instance exists (use get() instead). Use this only to retrieve an instance that you assume exists, where non-existence would be an actual error.
     *
     * @param clazz a persistent class
     * @param id a valid identifier of an existing persistent instance of the class
     * @return the persistent instance or proxy
     * @throws HibernateException
     */
	Object load(Class<?> clazz, Serializable id) throws HibernateException;
	/**
	 * Reattaches the given entity to the current session using LockMode.NONE
	 *
	 * @param entity to reattach
	 */
	void reattachEntityWithNoLock(IPojoGenEntity entity);
	/**
	 * Reattaches the given entities to the current session.
	 *
	 * @param entities to attach
	 */
	void reattachEntitiesWithNoLock(Collection<? extends IPojoGenEntity> entities);}

