package org.mraz.moose.dao.model.dao.moose.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.mraz.moose.dao.model.obj.moose.Aliases;
import org.springframework.stereotype.Repository;
import org.mraz.moose.dao.model.dao.moose.AliasesDao;
 
 
/**
 * DAO for table: Aliases.
 * @author autogenerated
 */
@Repository
public class AliasesDaoImpl extends GenericHibernateDaoImpl<Aliases, Date> implements AliasesDao {
	
	/** Constructor method. */
		public AliasesDaoImpl() {
			super(Aliases.class);
		}
	}

