package org.mraz.moose.dao.model.dao.moose.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.mraz.moose.dao.model.obj.moose.Attributes;
import org.springframework.stereotype.Repository;
import org.mraz.moose.dao.model.dao.moose.AttributesDao;
 
 
/**
 * DAO for table: Attributes.
 * @author autogenerated
 */
@Repository
public class AttributesDaoImpl extends GenericHibernateDaoImpl<Attributes, Long> implements AttributesDao {
	
	/** Constructor method. */
		public AttributesDaoImpl() {
			super(Attributes.class);
		}
	}

