package org.mraz.moose.dao.model.dao.moose.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.mraz.moose.dao.model.obj.moose.Deity;
import org.springframework.stereotype.Repository;
import org.mraz.moose.dao.model.dao.moose.DeityDao;
 
 
/**
 * DAO for table: Deity.
 * @author autogenerated
 */
@Repository
public class DeityDaoImpl extends GenericHibernateDaoImpl<Deity, Long> implements DeityDao {
	
	/** Constructor method. */
		public DeityDaoImpl() {
			super(Deity.class);
		}
	}

