package org.mraz.moose.dao.model.dao.moose.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.mraz.moose.dao.model.obj.moose.Group;
import org.springframework.stereotype.Repository;
import org.mraz.moose.dao.model.dao.moose.GroupDao;
 
 
/**
 * DAO for table: Group.
 * @author autogenerated
 */
@Repository
public class GroupDaoImpl extends GenericHibernateDaoImpl<Group, Long> implements GroupDao {
	
	/** Constructor method. */
		public GroupDaoImpl() {
			super(Group.class);
		}
	}

