package org.mraz.moose.dao.model.dao.moose.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.mraz.moose.dao.model.obj.moose.GroupSkills;
import org.springframework.stereotype.Repository;
import org.mraz.moose.dao.model.dao.moose.GroupSkillsDao;
 
 
/**
 * DAO for table: GroupSkills.
 * @author autogenerated
 */
@Repository
public class GroupSkillsDaoImpl extends GenericHibernateDaoImpl<GroupSkills, Long> implements GroupSkillsDao {
	
	/** Constructor method. */
		public GroupSkillsDaoImpl() {
			super(GroupSkills.class);
		}
	}

