package org.mraz.moose.dao.model.dao.moose.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.mraz.moose.dao.model.obj.moose.PlayerGladiator;
import org.springframework.stereotype.Repository;
import org.mraz.moose.dao.model.dao.moose.PlayerGladiatorDao;
 
 
/**
 * DAO for table: PlayerGladiator.
 * @author autogenerated
 */
@Repository
public class PlayerGladiatorDaoImpl extends GenericHibernateDaoImpl<PlayerGladiator, Date> implements PlayerGladiatorDao {
	
	/** Constructor method. */
		public PlayerGladiatorDaoImpl() {
			super(PlayerGladiator.class);
		}
	}

