package org.mraz.moose.dao.model.dao.moose.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.mraz.moose.dao.model.obj.moose.PlayerNotes;
import org.springframework.stereotype.Repository;
import org.mraz.moose.dao.model.dao.moose.PlayerNotesDao;
 
 
/**
 * DAO for table: PlayerNotes.
 * @author autogenerated
 */
@Repository
public class PlayerNotesDaoImpl extends GenericHibernateDaoImpl<PlayerNotes, Date> implements PlayerNotesDao {
	
	/** Constructor method. */
		public PlayerNotesDaoImpl() {
			super(PlayerNotes.class);
		}
	}

