package org.mraz.moose.dao.model.dao.moose.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.mraz.moose.dao.model.obj.moose.PlayerLasts;
import org.springframework.stereotype.Repository;
import org.mraz.moose.dao.model.dao.moose.PlayerLastsDao;
 
 
/**
 * DAO for table: PlayerLasts.
 * @author autogenerated
 */
@Repository
public class PlayerLastsDaoImpl extends GenericHibernateDaoImpl<PlayerLasts, Date> implements PlayerLastsDao {
	
	/** Constructor method. */
		public PlayerLastsDaoImpl() {
			super(PlayerLasts.class);
		}
	}

