package org.mraz.moose.dao.model.dao.moose.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.mraz.moose.dao.model.obj.moose.PlayerGroup;
import org.springframework.stereotype.Repository;
import org.mraz.moose.dao.model.dao.moose.PlayerGroupDao;
 
 
/**
 * DAO for table: PlayerGroup.
 * @author autogenerated
 */
@Repository
public class PlayerGroupDaoImpl extends GenericHibernateDaoImpl<PlayerGroup, Date> implements PlayerGroupDao {
	
	/** Constructor method. */
		public PlayerGroupDaoImpl() {
			super(PlayerGroup.class);
		}
	}

