package org.mraz.moose.dao.model.dao.moose.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.mraz.moose.dao.model.obj.moose.PlayerDeity;
import org.springframework.stereotype.Repository;
import org.mraz.moose.dao.model.dao.moose.PlayerDeityDao;
 
 
/**
 * DAO for table: PlayerDeity.
 * @author autogenerated
 */
@Repository
public class PlayerDeityDaoImpl extends GenericHibernateDaoImpl<PlayerDeity, Date> implements PlayerDeityDao {
	
	/** Constructor method. */
		public PlayerDeityDaoImpl() {
			super(PlayerDeity.class);
		}
	}

