package org.mraz.moose.dao.model.dao.moose.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.mraz.moose.dao.model.obj.moose.PlayerStats;
import org.springframework.stereotype.Repository;
import org.mraz.moose.dao.model.dao.moose.PlayerStatsDao;
 
 
/**
 * DAO for table: PlayerStats.
 * @author autogenerated
 */
@Repository
public class PlayerStatsDaoImpl extends GenericHibernateDaoImpl<PlayerStats, Date> implements PlayerStatsDao {
	
	/** Constructor method. */
		public PlayerStatsDaoImpl() {
			super(PlayerStats.class);
		}
	}

