package org.mraz.moose.dao.model.dao.moose.impl;

import com.felees.hbnpojogen.persistence.impl.GenericHibernateDaoImpl;
import org.mraz.moose.dao.model.obj.moose.SkillSpell;
import org.springframework.stereotype.Repository;
import org.mraz.moose.dao.model.dao.moose.SkillSpellDao;
 
 
/**
 * DAO for table: SkillSpell.
 * @author autogenerated
 */
@Repository
public class SkillSpellDaoImpl extends GenericHibernateDaoImpl<SkillSpell, Long> implements SkillSpellDao {
	
	/** Constructor method. */
		public SkillSpellDaoImpl() {
			super(SkillSpell.class);
		}
	}

