package org.mraz.moose.factories.moose;

import org.mraz.moose.model.obj.moose.*;
import org.springframework.stereotype.Component;



/** 
 * DAO factory implementation.
 * @author autogenerated
 */
@Component
public class MooseDataPoolFactory {
	/** DB commit order. */
	private static final String[] commitOrder = new String[]{"Player"};

    /**
     * Data pool factory for Player.
     * @return PlayerA Player object
     */
    public static Player getPlayer() {

        Player player = new Player();    
        
        player.setId(BasicDataGenerator.generateRandomString(20));
        player.setName(BasicDataGenerator.generateRandomString(20));

        return player;
    }
    /** Returns the commit order of this database. 
	 * Useful for iterating through the classes for deletion in the right order. 
	 * @return String[] list of classes
	 */
	public static String[] getDBCommitOrder() {
		return commitOrder;
	}
}