package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.Aliases;
 
/**
 * DAO interface for table: Aliases.
 * @author autogenerated
 */
public interface AliasesDao extends GenericDAO<Aliases,  Date>  {
	// constructor only
}

