package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.Attributes;
 
/**
 * DAO interface for table: Attributes.
 * @author autogenerated
 */
public interface AttributesDao extends GenericDAO<Attributes,  Long>  {
	// constructor only
}

