package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.Clans;
 
/**
 * DAO interface for table: Clans.
 * @author autogenerated
 */
public interface ClansDao extends GenericDAO<Clans,  Long>  {
	// constructor only
}

