package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.Deity;
 
/**
 * DAO interface for table: Deity.
 * @author autogenerated
 */
public interface DeityDao extends GenericDAO<Deity,  Long>  {
	// constructor only
}

