package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.Group;
 
/**
 * DAO interface for table: Group.
 * @author autogenerated
 */
public interface GroupDao extends GenericDAO<Group,  Long>  {
	// constructor only
}

