package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.GroupSkills;
 
/**
 * DAO interface for table: GroupSkills.
 * @author autogenerated
 */
public interface GroupSkillsDao extends GenericDAO<GroupSkills,  Long>  {
	// constructor only
}

