package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.PlayerGladiator;
 
/**
 * DAO interface for table: PlayerGladiator.
 * @author autogenerated
 */
public interface PlayerGladiatorDao extends GenericDAO<PlayerGladiator,  Date>  {
	// constructor only
}

