package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.PlayerStats;
 
/**
 * DAO interface for table: PlayerStats.
 * @author autogenerated
 */
public interface PlayerStatsDao extends GenericDAO<PlayerStats,  Date>  {
	// constructor only
}

