package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.PlayerNotes;
 
/**
 * DAO interface for table: PlayerNotes.
 * @author autogenerated
 */
public interface PlayerNotesDao extends GenericDAO<PlayerNotes,  Date>  {
	// constructor only
}

