package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.PlayerDeity;
 
/**
 * DAO interface for table: PlayerDeity.
 * @author autogenerated
 */
public interface PlayerDeityDao extends GenericDAO<PlayerDeity,  Date>  {
	// constructor only
}

