package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.PlayerSkills;
 
/**
 * DAO interface for table: PlayerSkills.
 * @author autogenerated
 */
public interface PlayerSkillsDao extends GenericDAO<PlayerSkills,  Date>  {
	// constructor only
}

