package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.PlayerLasts;
 
/**
 * DAO interface for table: PlayerLasts.
 * @author autogenerated
 */
public interface PlayerLastsDao extends GenericDAO<PlayerLasts,  Date>  {
	// constructor only
}

