package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.PlayerGroup;
 
/**
 * DAO interface for table: PlayerGroup.
 * @author autogenerated
 */
public interface PlayerGroupDao extends GenericDAO<PlayerGroup,  Date>  {
	// constructor only
}

