package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.Races;
 
/**
 * DAO interface for table: Races.
 * @author autogenerated
 */
public interface RacesDao extends GenericDAO<Races,  Long>  {
	// constructor only
}

