package org.mraz.moose.dao.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.dao.model.obj.moose.SkillSpell;
 
/**
 * DAO interface for table: SkillSpell.
 * @author autogenerated
 */
public interface SkillSpellDao extends GenericDAO<SkillSpell,  Long>  {
	// constructor only
}

