package org.mraz.moose.model.dao.moose;

import com.felees.hbnpojogen.persistence.GenericDAO;
import org.mraz.moose.model.obj.moose.Player;
 
/**
 * DAO interface for table: Player.
 * @author autogenerated
 */
public interface PlayerDao extends GenericDAO<Player,  String>  {
	// constructor only
}

