package org.mraz.moosehead.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * Dummy POJO used for testing.
 */
public class CharacterPojo implements Serializable {

	/**
	 * Version UID for Serialization
	 */
	private static final long serialVersionUID = 1;

	/**
	 * Identity is generated by DB.  From 0-BIGINT.
	 */
	private Long identity = 0L;

	/**
	 * Date the object was created
	 */
	private Date timestamp = new Date();

	/**
	 * @param identity the identity to set
	 */
	public void setIdentity(Long identity) {
		this.identity = identity;
	}

	/**
	 * @return the identity
	 */
	public Long getIdentity() {
		return identity;
	}

	/**
	 * @param timestamp the timestamp to set
	 */
	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	/**
	 * @return the timestamp
	 */
	public Date getTimestamp() {
		return timestamp;
	}

}
