package org.mraz.moose.dao.enums.db.moose;
import java.util.Map;
import java.util.HashMap;
import com.felees.hbnpojogen.persistence.impl.StringValuedEnum;
/**
 * Defines the PlayerTrueGenderEnum enumeration.
 * 
 * @author autogenerated
 *
 */
public enum PlayerTrueGenderEnum  implements StringValuedEnum {

	/** Enum Constant. */
	MALE("male"),
	/** Enum Constant. */
	FEMALE("female"),
	/** Enum Constant. */
	NONE("none");
	/**
	 * Internal storage of status field value, see the Enum spec for
 	 * clarification.
 	 */
	private final String status;
	
	/**
	 * Enum constructor for ActiveState.
	 * @param state Value.
	 */
	PlayerTrueGenderEnum(final String state) {
		this.status = state;
	}
	
	/** Construct a map for reverse lookup. */
	private static Map<String, PlayerTrueGenderEnum> valueMap = new HashMap<String, PlayerTrueGenderEnum>();

    static {
    	// construct hashmap for later possible use.
        for (PlayerTrueGenderEnum unit : values()) {
            valueMap.put(unit.getValue(), unit);
        }
    }
    
	/**
	 * Current string value stored in the enum.
	 * 
	 * @return string value.
	 */
	public String getValue() {
		return this.status;
	}

	/**
     * Perform a reverse lookup (given a value, obtain the enum).
     * 
     * @param value to search
     * @return Enum object.
     */
    public static PlayerTrueGenderEnum lookupEnum(String value) {
        return PlayerTrueGenderEnum.valueMap.get(value);
    }
}
