package org.mraz.moose.dao.factories.moose;

import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.BeanNameAware;

import org.mraz.moose.dao.model.dao.moose.*;

/** 
 * DAO factory implementation.
 * @author autogenerated
 */
@Component
public class HibernateMooseDaoFactory implements ApplicationContextAware, BeanNameAware {
	/** Placeholder for an instance. */
	private static HibernateMooseDaoFactory instance;
	/** Internal state. */
	private static ApplicationContext context = null;
	/** Bean Name. */
	private static String beanName;

	/** Return an instance of this class.
	 * @return an instance of this class
	 */
	public static synchronized HibernateMooseDaoFactory getInstance() {
		if (instance == null) {
			instance = (HibernateMooseDaoFactory) context.getBean(beanName);
		}
		return instance;
	}

	/**
	 * Sets a Spring Application Context object.
  	 * @param ctxt ApplicationContext to set
	 * @throws BeansException on spring error
	 */
	@Autowired
	public void setApplicationContext(ApplicationContext ctxt)
			throws BeansException 
	{
		context = ctxt;
	}

	/**
	* 
	* {@inheritDoc}
	* 
	* @see org.springframework.beans.factory.BeanNameAware#setBeanName(java.lang.String)
	*/
	public void setBeanName(String name) {
		beanName = name;
	}

	/**
	 * Return the requested bean from the context, throwing a RuntimeException on error.
	 *
	 * @param beanName to return
	 * @return the bean requested.
	 */
	public static Object getBean(String beanName) {
		Object result = context.getBean(beanName);
		if (result == null) { 
			throw new IllegalStateException(String.format("Could not find bean '%s'. Did you set the right component scanning?", beanName));
		} 
		
		return result;
	}

	
	/**
	 * Returns a AliasesDao instance.
	 * 
	 * @return a AliasesDao instance
	 */
	public static AliasesDao getAliasesDao() {
		return (AliasesDao) getBean("aliasesDaoImpl"); 
	}
	/**
	 * Returns a AttributesDao instance.
	 * 
	 * @return a AttributesDao instance
	 */
	public static AttributesDao getAttributesDao() {
		return (AttributesDao) getBean("attributesDaoImpl"); 
	}
	/**
	 * Returns a ClansDao instance.
	 * 
	 * @return a ClansDao instance
	 */
	public static ClansDao getClansDao() {
		return (ClansDao) getBean("clansDaoImpl"); 
	}
	/**
	 * Returns a DeityDao instance.
	 * 
	 * @return a DeityDao instance
	 */
	public static DeityDao getDeityDao() {
		return (DeityDao) getBean("deityDaoImpl"); 
	}
	/**
	 * Returns a GroupDao instance.
	 * 
	 * @return a GroupDao instance
	 */
	public static GroupDao getGroupDao() {
		return (GroupDao) getBean("groupDaoImpl"); 
	}
	/**
	 * Returns a GroupSkillsDao instance.
	 * 
	 * @return a GroupSkillsDao instance
	 */
	public static GroupSkillsDao getGroupSkillsDao() {
		return (GroupSkillsDao) getBean("groupSkillsDaoImpl"); 
	}
	/**
	 * Returns a PlayerDao instance.
	 * 
	 * @return a PlayerDao instance
	 */
	public static PlayerDao getPlayerDao() {
		return (PlayerDao) getBean("playerDaoImpl"); 
	}
	/**
	 * Returns a PlayerDeityDao instance.
	 * 
	 * @return a PlayerDeityDao instance
	 */
	public static PlayerDeityDao getPlayerDeityDao() {
		return (PlayerDeityDao) getBean("playerDeityDaoImpl"); 
	}
	/**
	 * Returns a PlayerGladiatorDao instance.
	 * 
	 * @return a PlayerGladiatorDao instance
	 */
	public static PlayerGladiatorDao getPlayerGladiatorDao() {
		return (PlayerGladiatorDao) getBean("playerGladiatorDaoImpl"); 
	}
	/**
	 * Returns a PlayerGroupDao instance.
	 * 
	 * @return a PlayerGroupDao instance
	 */
	public static PlayerGroupDao getPlayerGroupDao() {
		return (PlayerGroupDao) getBean("playerGroupDaoImpl"); 
	}
	/**
	 * Returns a PlayerLastsDao instance.
	 * 
	 * @return a PlayerLastsDao instance
	 */
	public static PlayerLastsDao getPlayerLastsDao() {
		return (PlayerLastsDao) getBean("playerLastsDaoImpl"); 
	}
	/**
	 * Returns a PlayerNotesDao instance.
	 * 
	 * @return a PlayerNotesDao instance
	 */
	public static PlayerNotesDao getPlayerNotesDao() {
		return (PlayerNotesDao) getBean("playerNotesDaoImpl"); 
	}
	/**
	 * Returns a PlayerSkillsDao instance.
	 * 
	 * @return a PlayerSkillsDao instance
	 */
	public static PlayerSkillsDao getPlayerSkillsDao() {
		return (PlayerSkillsDao) getBean("playerSkillsDaoImpl"); 
	}
	/**
	 * Returns a PlayerStatsDao instance.
	 * 
	 * @return a PlayerStatsDao instance
	 */
	public static PlayerStatsDao getPlayerStatsDao() {
		return (PlayerStatsDao) getBean("playerStatsDaoImpl"); 
	}
	/**
	 * Returns a RacesDao instance.
	 * 
	 * @return a RacesDao instance
	 */
	public static RacesDao getRacesDao() {
		return (RacesDao) getBean("racesDaoImpl"); 
	}
	/**
	 * Returns a SkillSpellDao instance.
	 * 
	 * @return a SkillSpellDao instance
	 */
	public static SkillSpellDao getSkillSpellDao() {
		return (SkillSpellDao) getBean("skillSpellDaoImpl"); 
	}

}
