package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

/**
 * Aliases generated by hbm2java
 */
public class Aliases implements java.io.Serializable {

	private Integer playerId;
	private Player player;
	private String name;
	private String value;

	public Aliases() {
	}

	public Aliases(Player player, String name) {
		this.player = player;
		this.name = name;
	}

	public Aliases(Player player, String name, String value) {
		this.player = player;
		this.name = name;
		this.value = value;
	}

	public Integer getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
