package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

/**
 * Clans generated by hbm2java
 */
public class Clans implements java.io.Serializable {

	private Integer clanId;
	private String name;
	private String whoName;
	private Short hallVnum;
	private boolean hidden;
	private boolean independent;
	private boolean pvp;

	public Clans() {
	}

	public Clans(String name, String whoName, boolean hidden,
			boolean independent, boolean pvp) {
		this.name = name;
		this.whoName = whoName;
		this.hidden = hidden;
		this.independent = independent;
		this.pvp = pvp;
	}

	public Clans(String name, String whoName, Short hallVnum, boolean hidden,
			boolean independent, boolean pvp) {
		this.name = name;
		this.whoName = whoName;
		this.hallVnum = hallVnum;
		this.hidden = hidden;
		this.independent = independent;
		this.pvp = pvp;
	}

	public Integer getClanId() {
		return this.clanId;
	}

	public void setClanId(Integer clanId) {
		this.clanId = clanId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getWhoName() {
		return this.whoName;
	}

	public void setWhoName(String whoName) {
		this.whoName = whoName;
	}

	public Short getHallVnum() {
		return this.hallVnum;
	}

	public void setHallVnum(Short hallVnum) {
		this.hallVnum = hallVnum;
	}

	public boolean isHidden() {
		return this.hidden;
	}

	public void setHidden(boolean hidden) {
		this.hidden = hidden;
	}

	public boolean isIndependent() {
		return this.independent;
	}

	public void setIndependent(boolean independent) {
		this.independent = independent;
	}

	public boolean isPvp() {
		return this.pvp;
	}

	public void setPvp(boolean pvp) {
		this.pvp = pvp;
	}

}
