package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Deity generated by hbm2java
 */
public class Deity implements java.io.Serializable {

	private Integer deityId;
	private String name;
	private Set playerDeities = new HashSet(0);

	public Deity() {
	}

	public Deity(String name) {
		this.name = name;
	}

	public Deity(String name, Set playerDeities) {
		this.name = name;
		this.playerDeities = playerDeities;
	}

	public Integer getDeityId() {
		return this.deityId;
	}

	public void setDeityId(Integer deityId) {
		this.deityId = deityId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getPlayerDeities() {
		return this.playerDeities;
	}

	public void setPlayerDeities(Set playerDeities) {
		this.playerDeities = playerDeities;
	}

}
