package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable {

	private Integer id;
	private String name;
	private GroupSkills groupSkills;

	public Group() {
	}

	public Group(String name) {
		this.name = name;
	}

	public Group(String name, GroupSkills groupSkills) {
		this.name = name;
		this.groupSkills = groupSkills;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public GroupSkills getGroupSkills() {
		return this.groupSkills;
	}

	public void setGroupSkills(GroupSkills groupSkills) {
		this.groupSkills = groupSkills;
	}

}
