package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

/**
 * GroupSkills generated by hbm2java
 */
public class GroupSkills implements java.io.Serializable {

	private int groupId;
	private SkillSpell skillSpell;
	private Group group;

	public GroupSkills() {
	}

	public GroupSkills(SkillSpell skillSpell, Group group) {
		this.skillSpell = skillSpell;
		this.group = group;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public SkillSpell getSkillSpell() {
		return this.skillSpell;
	}

	public void setSkillSpell(SkillSpell skillSpell) {
		this.skillSpell = skillSpell;
	}

	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

}
