package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

/**
 * PlayerStats generated by hbm2java
 */
public class PlayerStats implements java.io.Serializable {

	private Integer playerId;
	private Player player;
	private short hp;
	private short maxHp;
	private short mana;
	private short maxMana;
	private short move;
	private short maxMove;
	private int gold;
	private int silver;
	private int bank;
	private short incognito;
	private short invisible;
	private short practice;
	private short training;
	private short skill;
	private short savingThrow;
	private int alignment;
	private short hitroll;
	private short damroll;
	private short secondHitroll;
	private short secondDamroll;
	private short ac0;
	private short ac1;
	private short ac2;
	private short ac3;
	private short wimpy;

	public PlayerStats() {
	}

	public PlayerStats(Player player, short hp, short maxHp, short mana,
			short maxMana, short move, short maxMove, int gold, int silver,
			int bank, short incognito, short invisible, short practice,
			short training, short skill, short savingThrow, int alignment,
			short hitroll, short damroll, short secondHitroll,
			short secondDamroll, short ac0, short ac1, short ac2, short ac3,
			short wimpy) {
		this.player = player;
		this.hp = hp;
		this.maxHp = maxHp;
		this.mana = mana;
		this.maxMana = maxMana;
		this.move = move;
		this.maxMove = maxMove;
		this.gold = gold;
		this.silver = silver;
		this.bank = bank;
		this.incognito = incognito;
		this.invisible = invisible;
		this.practice = practice;
		this.training = training;
		this.skill = skill;
		this.savingThrow = savingThrow;
		this.alignment = alignment;
		this.hitroll = hitroll;
		this.damroll = damroll;
		this.secondHitroll = secondHitroll;
		this.secondDamroll = secondDamroll;
		this.ac0 = ac0;
		this.ac1 = ac1;
		this.ac2 = ac2;
		this.ac3 = ac3;
		this.wimpy = wimpy;
	}

	public Integer getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

	public short getHp() {
		return this.hp;
	}

	public void setHp(short hp) {
		this.hp = hp;
	}

	public short getMaxHp() {
		return this.maxHp;
	}

	public void setMaxHp(short maxHp) {
		this.maxHp = maxHp;
	}

	public short getMana() {
		return this.mana;
	}

	public void setMana(short mana) {
		this.mana = mana;
	}

	public short getMaxMana() {
		return this.maxMana;
	}

	public void setMaxMana(short maxMana) {
		this.maxMana = maxMana;
	}

	public short getMove() {
		return this.move;
	}

	public void setMove(short move) {
		this.move = move;
	}

	public short getMaxMove() {
		return this.maxMove;
	}

	public void setMaxMove(short maxMove) {
		this.maxMove = maxMove;
	}

	public int getGold() {
		return this.gold;
	}

	public void setGold(int gold) {
		this.gold = gold;
	}

	public int getSilver() {
		return this.silver;
	}

	public void setSilver(int silver) {
		this.silver = silver;
	}

	public int getBank() {
		return this.bank;
	}

	public void setBank(int bank) {
		this.bank = bank;
	}

	public short getIncognito() {
		return this.incognito;
	}

	public void setIncognito(short incognito) {
		this.incognito = incognito;
	}

	public short getInvisible() {
		return this.invisible;
	}

	public void setInvisible(short invisible) {
		this.invisible = invisible;
	}

	public short getPractice() {
		return this.practice;
	}

	public void setPractice(short practice) {
		this.practice = practice;
	}

	public short getTraining() {
		return this.training;
	}

	public void setTraining(short training) {
		this.training = training;
	}

	public short getSkill() {
		return this.skill;
	}

	public void setSkill(short skill) {
		this.skill = skill;
	}

	public short getSavingThrow() {
		return this.savingThrow;
	}

	public void setSavingThrow(short savingThrow) {
		this.savingThrow = savingThrow;
	}

	public int getAlignment() {
		return this.alignment;
	}

	public void setAlignment(int alignment) {
		this.alignment = alignment;
	}

	public short getHitroll() {
		return this.hitroll;
	}

	public void setHitroll(short hitroll) {
		this.hitroll = hitroll;
	}

	public short getDamroll() {
		return this.damroll;
	}

	public void setDamroll(short damroll) {
		this.damroll = damroll;
	}

	public short getSecondHitroll() {
		return this.secondHitroll;
	}

	public void setSecondHitroll(short secondHitroll) {
		this.secondHitroll = secondHitroll;
	}

	public short getSecondDamroll() {
		return this.secondDamroll;
	}

	public void setSecondDamroll(short secondDamroll) {
		this.secondDamroll = secondDamroll;
	}

	public short getAc0() {
		return this.ac0;
	}

	public void setAc0(short ac0) {
		this.ac0 = ac0;
	}

	public short getAc1() {
		return this.ac1;
	}

	public void setAc1(short ac1) {
		this.ac1 = ac1;
	}

	public short getAc2() {
		return this.ac2;
	}

	public void setAc2(short ac2) {
		this.ac2 = ac2;
	}

	public short getAc3() {
		return this.ac3;
	}

	public void setAc3(short ac3) {
		this.ac3 = ac3;
	}

	public short getWimpy() {
		return this.wimpy;
	}

	public void setWimpy(short wimpy) {
		this.wimpy = wimpy;
	}

}
