package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Player generated by hbm2java
 */
public class Player implements java.io.Serializable {

	private Date id;
	private int version;
	private String name;
	private String surname;
	private String title;
	private String email;
	private String shortDesc;
	private String longDesc;
	private String description;
	private int raceId;
	private Integer clanId;
	private String gender;
	private int level;
	private Integer trust;
	private int played;
	private String password;
	private String bamfIn;
	private String bamfOut;
	private String whoname;
	private String trueGender;
	private Aliases aliases;
	private PlayerLasts playerLasts;
	private PlayerGladiator playerGladiator;
	private PlayerNotes playerNotes;
	private PlayerDeity playerDeity;
	private PlayerStats playerStats;
	private PlayerGroup playerGroup;
	private PlayerSkills playerSkills;

	public Player() {
	}

	public Player(Date id, String name, int raceId, String gender, int level,
			int played, String password) {
		this.id = id;
		this.name = name;
		this.raceId = raceId;
		this.gender = gender;
		this.level = level;
		this.played = played;
		this.password = password;
	}

	public Player(Date id, String name, String surname, String title,
			String email, String shortDesc, String longDesc,
			String description, int raceId, Integer clanId, String gender,
			int level, Integer trust, int played, String password,
			String bamfIn, String bamfOut, String whoname, String trueGender,
			Aliases aliases, PlayerLasts playerLasts,
			PlayerGladiator playerGladiator, PlayerNotes playerNotes,
			PlayerDeity playerDeity, PlayerStats playerStats,
			PlayerGroup playerGroup, PlayerSkills playerSkills) {
		this.id = id;
		this.name = name;
		this.surname = surname;
		this.title = title;
		this.email = email;
		this.shortDesc = shortDesc;
		this.longDesc = longDesc;
		this.description = description;
		this.raceId = raceId;
		this.clanId = clanId;
		this.gender = gender;
		this.level = level;
		this.trust = trust;
		this.played = played;
		this.password = password;
		this.bamfIn = bamfIn;
		this.bamfOut = bamfOut;
		this.whoname = whoname;
		this.trueGender = trueGender;
		this.aliases = aliases;
		this.playerLasts = playerLasts;
		this.playerGladiator = playerGladiator;
		this.playerNotes = playerNotes;
		this.playerDeity = playerDeity;
		this.playerStats = playerStats;
		this.playerGroup = playerGroup;
		this.playerSkills = playerSkills;
	}

	public Date getId() {
		return this.id;
	}

	public void setId(Date id) {
		this.id = id;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public String getLongDesc() {
		return this.longDesc;
	}

	public void setLongDesc(String longDesc) {
		this.longDesc = longDesc;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getRaceId() {
		return this.raceId;
	}

	public void setRaceId(int raceId) {
		this.raceId = raceId;
	}

	public Integer getClanId() {
		return this.clanId;
	}

	public void setClanId(Integer clanId) {
		this.clanId = clanId;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public Integer getTrust() {
		return this.trust;
	}

	public void setTrust(Integer trust) {
		this.trust = trust;
	}

	public int getPlayed() {
		return this.played;
	}

	public void setPlayed(int played) {
		this.played = played;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getBamfIn() {
		return this.bamfIn;
	}

	public void setBamfIn(String bamfIn) {
		this.bamfIn = bamfIn;
	}

	public String getBamfOut() {
		return this.bamfOut;
	}

	public void setBamfOut(String bamfOut) {
		this.bamfOut = bamfOut;
	}

	public String getWhoname() {
		return this.whoname;
	}

	public void setWhoname(String whoname) {
		this.whoname = whoname;
	}

	public String getTrueGender() {
		return this.trueGender;
	}

	public void setTrueGender(String trueGender) {
		this.trueGender = trueGender;
	}

	public Aliases getAliases() {
		return this.aliases;
	}

	public void setAliases(Aliases aliases) {
		this.aliases = aliases;
	}

	public PlayerLasts getPlayerLasts() {
		return this.playerLasts;
	}

	public void setPlayerLasts(PlayerLasts playerLasts) {
		this.playerLasts = playerLasts;
	}

	public PlayerGladiator getPlayerGladiator() {
		return this.playerGladiator;
	}

	public void setPlayerGladiator(PlayerGladiator playerGladiator) {
		this.playerGladiator = playerGladiator;
	}

	public PlayerNotes getPlayerNotes() {
		return this.playerNotes;
	}

	public void setPlayerNotes(PlayerNotes playerNotes) {
		this.playerNotes = playerNotes;
	}

	public PlayerDeity getPlayerDeity() {
		return this.playerDeity;
	}

	public void setPlayerDeity(PlayerDeity playerDeity) {
		this.playerDeity = playerDeity;
	}

	public PlayerStats getPlayerStats() {
		return this.playerStats;
	}

	public void setPlayerStats(PlayerStats playerStats) {
		this.playerStats = playerStats;
	}

	public PlayerGroup getPlayerGroup() {
		return this.playerGroup;
	}

	public void setPlayerGroup(PlayerGroup playerGroup) {
		this.playerGroup = playerGroup;
	}

	public PlayerSkills getPlayerSkills() {
		return this.playerSkills;
	}

	public void setPlayerSkills(PlayerSkills playerSkills) {
		this.playerSkills = playerSkills;
	}

}
