package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

/**
 * PlayerGroup generated by hbm2java
 */
public class PlayerGroup implements java.io.Serializable {

	private Integer playerId;
	private Player player;

	public PlayerGroup() {
	}

	public PlayerGroup(Player player) {
		this.player = player;
	}

	public Integer getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

}
