package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PlayerLasts generated by hbm2java
 */
public class PlayerLasts implements java.io.Serializable {

	private Date playerId;
	private Player player;
	private Date killedBy;
	private Date killed;
	private Date attacked;
	private Date attackedBy;
	private int attackedByTimer;
	private Date combat;
	private Date killedDt;
	private Date deathDt;
	private Date login;

	public PlayerLasts() {
	}

	public PlayerLasts(Player player, Date killedBy, Date killed,
			Date attacked, Date attackedBy, int attackedByTimer, Date combat,
			Date login) {
		this.player = player;
		this.killedBy = killedBy;
		this.killed = killed;
		this.attacked = attacked;
		this.attackedBy = attackedBy;
		this.attackedByTimer = attackedByTimer;
		this.combat = combat;
		this.login = login;
	}

	public PlayerLasts(Player player, Date killedBy, Date killed,
			Date attacked, Date attackedBy, int attackedByTimer, Date combat,
			Date killedDt, Date deathDt, Date login) {
		this.player = player;
		this.killedBy = killedBy;
		this.killed = killed;
		this.attacked = attacked;
		this.attackedBy = attackedBy;
		this.attackedByTimer = attackedByTimer;
		this.combat = combat;
		this.killedDt = killedDt;
		this.deathDt = deathDt;
		this.login = login;
	}

	public Date getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Date playerId) {
		this.playerId = playerId;
	}

	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

	public Date getKilledBy() {
		return this.killedBy;
	}

	public void setKilledBy(Date killedBy) {
		this.killedBy = killedBy;
	}

	public Date getKilled() {
		return this.killed;
	}

	public void setKilled(Date killed) {
		this.killed = killed;
	}

	public Date getAttacked() {
		return this.attacked;
	}

	public void setAttacked(Date attacked) {
		this.attacked = attacked;
	}

	public Date getAttackedBy() {
		return this.attackedBy;
	}

	public void setAttackedBy(Date attackedBy) {
		this.attackedBy = attackedBy;
	}

	public int getAttackedByTimer() {
		return this.attackedByTimer;
	}

	public void setAttackedByTimer(int attackedByTimer) {
		this.attackedByTimer = attackedByTimer;
	}

	public Date getCombat() {
		return this.combat;
	}

	public void setCombat(Date combat) {
		this.combat = combat;
	}

	public Date getKilledDt() {
		return this.killedDt;
	}

	public void setKilledDt(Date killedDt) {
		this.killedDt = killedDt;
	}

	public Date getDeathDt() {
		return this.deathDt;
	}

	public void setDeathDt(Date deathDt) {
		this.deathDt = deathDt;
	}

	public Date getLogin() {
		return this.login;
	}

	public void setLogin(Date login) {
		this.login = login;
	}

}
