package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

/**
 * PlayerNotes generated by hbm2java
 */
public class PlayerNotes implements java.io.Serializable {

	private Integer playerId;
	private Player player;
	private int note;
	private int idea;
	private int penalty;
	private int news;
	private int change;
	private int ooc;
	private int bug;
	private int clan;
	private int immortal;
	private int question;

	public PlayerNotes() {
	}

	public PlayerNotes(Player player, int note, int idea, int penalty,
			int news, int change, int ooc, int bug, int clan, int immortal,
			int question) {
		this.player = player;
		this.note = note;
		this.idea = idea;
		this.penalty = penalty;
		this.news = news;
		this.change = change;
		this.ooc = ooc;
		this.bug = bug;
		this.clan = clan;
		this.immortal = immortal;
		this.question = question;
	}

	public Integer getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

	public int getNote() {
		return this.note;
	}

	public void setNote(int note) {
		this.note = note;
	}

	public int getIdea() {
		return this.idea;
	}

	public void setIdea(int idea) {
		this.idea = idea;
	}

	public int getPenalty() {
		return this.penalty;
	}

	public void setPenalty(int penalty) {
		this.penalty = penalty;
	}

	public int getNews() {
		return this.news;
	}

	public void setNews(int news) {
		this.news = news;
	}

	public int getChange() {
		return this.change;
	}

	public void setChange(int change) {
		this.change = change;
	}

	public int getOoc() {
		return this.ooc;
	}

	public void setOoc(int ooc) {
		this.ooc = ooc;
	}

	public int getBug() {
		return this.bug;
	}

	public void setBug(int bug) {
		this.bug = bug;
	}

	public int getClan() {
		return this.clan;
	}

	public void setClan(int clan) {
		this.clan = clan;
	}

	public int getImmortal() {
		return this.immortal;
	}

	public void setImmortal(int immortal) {
		this.immortal = immortal;
	}

	public int getQuestion() {
		return this.question;
	}

	public void setQuestion(int question) {
		this.question = question;
	}

}
