package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

/**
 * PlayerGladiator generated by hbm2java
 */
public class PlayerGladiator implements java.io.Serializable {

	private Integer playerId;
	private Player player;
	private int wins;
	private int kills;
	private int teamWins;
	private int teamKills;
	private int games;
	private int teamGames;

	public PlayerGladiator() {
	}

	public PlayerGladiator(Player player, int wins, int kills, int teamWins,
			int teamKills, int games, int teamGames) {
		this.player = player;
		this.wins = wins;
		this.kills = kills;
		this.teamWins = teamWins;
		this.teamKills = teamKills;
		this.games = games;
		this.teamGames = teamGames;
	}

	public Integer getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

	public int getWins() {
		return this.wins;
	}

	public void setWins(int wins) {
		this.wins = wins;
	}

	public int getKills() {
		return this.kills;
	}

	public void setKills(int kills) {
		this.kills = kills;
	}

	public int getTeamWins() {
		return this.teamWins;
	}

	public void setTeamWins(int teamWins) {
		this.teamWins = teamWins;
	}

	public int getTeamKills() {
		return this.teamKills;
	}

	public void setTeamKills(int teamKills) {
		this.teamKills = teamKills;
	}

	public int getGames() {
		return this.games;
	}

	public void setGames(int games) {
		this.games = games;
	}

	public int getTeamGames() {
		return this.teamGames;
	}

	public void setTeamGames(int teamGames) {
		this.teamGames = teamGames;
	}

}
