package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

/**
 * PlayerSkills generated by hbm2java
 */
public class PlayerSkills implements java.io.Serializable {

	private Integer playerId;
	private SkillSpell skillSpell;
	private Player player;
	private short learnedPercent;

	public PlayerSkills() {
	}

	public PlayerSkills(SkillSpell skillSpell, Player player,
			short learnedPercent) {
		this.skillSpell = skillSpell;
		this.player = player;
		this.learnedPercent = learnedPercent;
	}

	public Integer getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Integer playerId) {
		this.playerId = playerId;
	}

	public SkillSpell getSkillSpell() {
		return this.skillSpell;
	}

	public void setSkillSpell(SkillSpell skillSpell) {
		this.skillSpell = skillSpell;
	}

	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

	public short getLearnedPercent() {
		return this.learnedPercent;
	}

	public void setLearnedPercent(short learnedPercent) {
		this.learnedPercent = learnedPercent;
	}

}
