package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PlayerDeity generated by hbm2java
 */
public class PlayerDeity implements java.io.Serializable {

	private Date playerId;
	private Player player;
	private Deity deity;
	private Date switchedTo;
	private int sacrificeCnt;

	public PlayerDeity() {
	}

	public PlayerDeity(Player player, Deity deity, Date switchedTo,
			int sacrificeCnt) {
		this.player = player;
		this.deity = deity;
		this.switchedTo = switchedTo;
		this.sacrificeCnt = sacrificeCnt;
	}

	public Date getPlayerId() {
		return this.playerId;
	}

	public void setPlayerId(Date playerId) {
		this.playerId = playerId;
	}

	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

	public Deity getDeity() {
		return this.deity;
	}

	public void setDeity(Deity deity) {
		this.deity = deity;
	}

	public Date getSwitchedTo() {
		return this.switchedTo;
	}

	public void setSwitchedTo(Date switchedTo) {
		this.switchedTo = switchedTo;
	}

	public int getSacrificeCnt() {
		return this.sacrificeCnt;
	}

	public void setSacrificeCnt(int sacrificeCnt) {
		this.sacrificeCnt = sacrificeCnt;
	}

}
