package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

/**
 * Races generated by hbm2java
 */
public class Races implements java.io.Serializable {

	private Integer raceId;
	private String name;
	private short statStr;
	private short statInt;
	private short statWis;
	private short statDex;
	private short statCon;
	private short statAgt;
	private short statEnd;
	private short statSoc;

	public Races() {
	}

	public Races(String name, short statStr, short statInt, short statWis,
			short statDex, short statCon, short statAgt, short statEnd,
			short statSoc) {
		this.name = name;
		this.statStr = statStr;
		this.statInt = statInt;
		this.statWis = statWis;
		this.statDex = statDex;
		this.statCon = statCon;
		this.statAgt = statAgt;
		this.statEnd = statEnd;
		this.statSoc = statSoc;
	}

	public Integer getRaceId() {
		return this.raceId;
	}

	public void setRaceId(Integer raceId) {
		this.raceId = raceId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public short getStatStr() {
		return this.statStr;
	}

	public void setStatStr(short statStr) {
		this.statStr = statStr;
	}

	public short getStatInt() {
		return this.statInt;
	}

	public void setStatInt(short statInt) {
		this.statInt = statInt;
	}

	public short getStatWis() {
		return this.statWis;
	}

	public void setStatWis(short statWis) {
		this.statWis = statWis;
	}

	public short getStatDex() {
		return this.statDex;
	}

	public void setStatDex(short statDex) {
		this.statDex = statDex;
	}

	public short getStatCon() {
		return this.statCon;
	}

	public void setStatCon(short statCon) {
		this.statCon = statCon;
	}

	public short getStatAgt() {
		return this.statAgt;
	}

	public void setStatAgt(short statAgt) {
		this.statAgt = statAgt;
	}

	public short getStatEnd() {
		return this.statEnd;
	}

	public void setStatEnd(short statEnd) {
		this.statEnd = statEnd;
	}

	public short getStatSoc() {
		return this.statSoc;
	}

	public void setStatSoc(short statSoc) {
		this.statSoc = statSoc;
	}

}
