package org.mraz.moose;

// Generated May 30, 2011 12:25:33 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * SkillSpell generated by hbm2java
 */
public class SkillSpell implements java.io.Serializable {

	private Integer sn;
	private Set groupSkillses = new HashSet(0);
	private Set playerSkillses = new HashSet(0);

	public SkillSpell() {
	}

	public SkillSpell(Set groupSkillses, Set playerSkillses) {
		this.groupSkillses = groupSkillses;
		this.playerSkillses = playerSkillses;
	}

	public Integer getSn() {
		return this.sn;
	}

	public void setSn(Integer sn) {
		this.sn = sn;
	}

	public Set getGroupSkillses() {
		return this.groupSkillses;
	}

	public void setGroupSkillses(Set groupSkillses) {
		this.groupSkillses = groupSkillses;
	}

	public Set getPlayerSkillses() {
		return this.playerSkillses;
	}

	public void setPlayerSkillses(Set playerSkillses) {
		this.playerSkillses = playerSkillses;
	}

}
